# Basic Plan
Make a variable that keeps track of the round that we are on. If today's date is after the next round load the next round and then use a script to get the points from the df. We will have to keep track of each qualifying, race, sprint qualifying, and sprint race. The goal is to plot each driver's fantasy points according to the f1 fantasy rules.

In [1]:
import fastf1
import pandas as pd
import time
from datetime import date, datetime
from scoring import quali_fantasy_score, quali_position

In [2]:

# For now we are going to just manually 
# get the session and maybe return to scheduled jobs later


session = fastf1.get_session(2026, 1, "Q")
session.load()
results = session.results.reset_index(drop = True, inplace = True)

# The columns I need for scoring are the driver, team, points, status
results_df = session.results[["Abbreviation", "TeamName","Q1","Q2","Q3"]]
results_df.index = results_df.index + 1

req         WARNING 	DEFAULT CACHE ENABLED! (463.07 MB) C:\Users\ethan\AppData\Local\Temp\fastf1

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	No lap data for driver 55
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '6', '16', '81', '1', '44', '30', '41', '5', '27', '87', '31', '10', '23', '43', '14', '11', '77', '18', '3', '55']

In [3]:
results_df

,Abbreviation,TeamName,Q1,Q2,Q3
1,RUS,Mercedes,0 days 00:01:19.507000,0 days 00:01:18.934000,0 days 00:01:18.518000
2,ANT,Mercedes,0 days 00:01:20.120000,0 days 00:01:19.435000,0 days 00:01:18.811000
3,HAD,Red Bull Racing,0 days 00:01:20.023000,0 days 00:01:19.653000,0 days 00:01:19.303000
4,LEC,Ferrari,0 days 00:01:20.226000,0 days 00:01:19.357000,0 days 00:01:19.327000
5,PIA,McLaren,0 days 00:01:19.664000,0 days 00:01:19.525000,0 days 00:01:19.380000
6,NOR,McLaren,0 days 00:01:20.010000,0 days 00:01:19.882000,0 days 00:01:19.475000
7,HAM,Ferrari,0 days 00:01:19.811000,0 days 00:01:19.921000,0 days 00:01:19.478000
8,LAW,Racing Bulls,0 days 00:01:20.491000,0 days 00:01:20.144000,0 days 00:01:19.994000
9,LIN,Racing Bulls,0 days 00:01:20.409000,0 days 00:01:19.971000,0 days 00:01:21.247000
10,BOR,Audi,0 days 00:01:20.495000,0 days 00:01:20.221000,NaT
11,HUL,Audi,0 days 00:01:21.024000,0 days 00:01:20.303000,NaT
12,BEA,Haas F1 Team,0 days 00:01:21.247000,0 days 00:01:20.311000,NaT
13,OCO,Haas F1 Team,0 days 00:01:20.759000,0 days 00:01:20.491000,NaT
14,GAS,Alpine,0 days 00:01:21.138000,0 days 00:01:20.501000,NaT
15,ALB,Williams,0 days 00:01:21.051000,0 days 00:01:20.941000,NaT
16,COL,Alpine,0 days 00:01:21.200000,0 days 00:01:21.270000,NaT
17,ALO,Aston Martin,0 days 00:01:21.969000,NaT,NaT
18,PER,Cadillac,0 days 00:01:22.605000,NaT,NaT
19,BOT,Cadillac,0 days 00:01:23.244000,NaT,NaT
20,STR,Aston Martin,NaT,NaT,NaT
21,VER,Red Bull Racing,NaT,NaT,NaT
22,SAI,Williams,NaT,NaT,NaT

In [4]:

drivers_score = {}
for row in results_df.itertuples():
    if not pd.isnull(row.Q1):
        drivers_score[row.Abbreviation] = row.Index
    else:
        drivers_score[row.Abbreviation] = "NC/DSQ"
drivers_score

{'RUS': 1,
 'ANT': 2,
 'HAD': 3,
 'LEC': 4,
 'PIA': 5,
 'NOR': 6,
 'HAM': 7,
 'LAW': 8,
 'LIN': 9,
 'BOR': 10,
 'HUL': 11,
 'BEA': 12,
 'OCO': 13,
 'GAS': 14,
 'ALB': 15,
 'COL': 16,
 'ALO': 17,
 'PER': 18,
 'BOT': 19,
 'STR': 'NC/DSQ',
 'VER': 'NC/DSQ',
 'SAI': 'NC/DSQ'}

In [5]:
score = quali_fantasy_score(quali_position(1))
score = quali_fantasy_score(quali_position(2), score)
score = quali_fantasy_score(quali_position(3), score)
score
# score = quali_fantasy_score(quali_position(2), score)
# quali_fantasy_score(quali_position(3), score)

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	No lap data for driver 55
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '6', '16', '81', '1', '44', '30', '41', '5', '27', '87', '31', '10', '23', '43', '14', '11', '77', '18', '3', '55']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '81', '1', '10', '3', '6', '87', '27', '43', '31', '30', '41', '5', '55', '23', '14', '77', '18', '11']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '81', '16', '1', '44', '10', '6', '5', '41', '3', '31', '27', '30', '43', '55', '23', '87', '11', '77', '14', '18']

{'RUS': 28,
 'ANT': 29,
 'HAD': 13,
 'LEC': 21,
 'PIA': 20,
 'NOR': 16,
 'HAM': 17,
 'LAW': 3,
 'LIN': 3,
 'BOR': 3,
 'HUL': 0,
 'BEA': 1,
 'OCO': 0,
 'GAS': 8,
 'ALB': 0,
 'COL': 0,
 'ALO': 0,
 'PER': 0,
 'BOT': 0,
 'STR': -5,
 'VER': -2,
 'SAI': -5}

In [6]:
race1 = fastf1.get_session(2026, 1, "R")
race1.load()

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

In [7]:
race1.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:23:06.801000,Finished,25.0,58.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:02.974000,Finished,18.0,58.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:15.519000,Finished,15.0,58.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,7.0,NaT,NaT,NaT,0 days 00:00:16.144000,Finished,12.0,58.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:51.741000,Finished,10.0,58.0
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,6.0,6,20.0,NaT,NaT,NaT,0 days 00:00:54.617000,Finished,8.0,58.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,7.0,7,12.0,NaT,NaT,NaT,0 days 00:00:04.593000,Lapped,6.0,57.0
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,8.0,8,9.0,NaT,NaT,NaT,0 days 00:00:11.816000,Lapped,4.0,57.0
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,9.0,9,10.0,NaT,NaT,NaT,0 days 00:00:12.775000,Lapped,2.0,57.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,10.0,10,14.0,NaT,NaT,NaT,0 days 00:00:29.027000,Lapped,1.0,57.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,11.0,11,13.0,NaT,NaT,NaT,0 days 00:00:29.850000,Lapped,0.0,57.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,12.0,12,15.0,NaT,NaT,NaT,0 days 00:00:56.075000,Lapped,0.0,57.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,13.0,13,8.0,NaT,NaT,NaT,0 days 00:00:57.173000,Lapped,0.0,57.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,14.0,14,16.0,NaT,NaT,NaT,0 days 00:00:08.487000,Lapped,0.0,56.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,15.0,15,21.0,NaT,NaT,NaT,0 days 00:00:36.886000,Lapped,0.0,56.0
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,16.0,16,18.0,NaT,NaT,NaT,0 days 00:00:07.850000,Lapped,0.0,55.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,17.0,R,22.0,NaT,NaT,NaT,NaT,Lapped,0.0,43.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,18.0,R,17.0,NaT,NaT,NaT,NaT,Retired,0.0,21.0
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,19.0,R,19.0,NaT,NaT,NaT,NaT,Retired,0.0,15.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,20.0,R,3.0,NaT,NaT,NaT,NaT,Retired,0.0,10.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,21.0,W,5.0,NaT,NaT,NaT,NaT,Did not start,0.0,0.0
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,22.0,W,11.0,NaT,NaT,NaT,NaT,Did not start,0.0,0.0